apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ include "aiops-platform.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: {{ include "aiops-platform.namespace" . }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: {{ include "aiops-platform.namespace" . }}
automountServiceAccountToken: false
